Feature/create meeting pull request 요청
lee1684/SKYTeam pull request #13
Opened 2024-04-28 16:17 UTC by jihwankim129

흠 빌드같은거 해서 테스트 해보고 되는지 확인해서 해보고 싶엇는데 그냥 back-end꺼 브랜치 가져와서 실행시키면 계속 오류가 뜨더라구요. db 연결 로컬 mysql로도 돌리고 이것저것 해봣는데... 테스트 해보고 싶은데 자꾸 계속 안되서 일단 PR 을 남기고 

이거 기존에 작성했던거 이미 back-end 에 있는 예시에 맞춰서 수정을 해서 올렸습니다.

근데 브랜치 가져왔더니 lombok getter setter가 활성화가 왜안되는진 모르겟지만 계속 에러가 떠서 무튼

결론: 테스트는 제대로 못했지만 합쳐도 될지 한번 봐주세요

2024-04-28 23:43 UTC, SyingSHY requested changes
일단 main으로 PR이 아니라 back-end로 PR입니다. 이 부분은 제가 직접 수정했습니다.

커밋 로그가 이렇게 남을 리가 없는데...?
그리고 pileuzsu 로컬 계정이신 거 같은데 git config user.email / user.name 확인 부탁드립니다.

여러모로 뭔가 잘못된 거 같은데 재검토 부탁 드립니다.

2024-04-29 00:50 UTC, lee1684 commented
9c06d46863a7bc28dc89158937c677fad0746b4a 이 커밋 하나만 추가하신 것 같은데 리베이스가 잘못된 것 같네요.
직접 하시다가 더 꼬일 수도 있어서 제가 푸쉬해놓겠습니다.

2024-04-29 04:43 UTC, jihwankim129 commented
내용이 많이 바껴서 리베이스보다 그냥 직접넣는게 더 빠른것 같아서 그냥 커밋 한개만 넣었어요.

머지 리퀘스트를 실수로 메인으로 했었군요

2024-04-29 04:45 UTC, jihwankim129 commented
계속 계정 왔다 갔다쓰다 보니깐 pileuszu 계정으로 들어갔군요

2024-04-29 05:07 UTC, lee1684 commented on back-end/src/main/java/kr/co/ssalon/domain/service/MeetingService.java
> +        }
이 부분 return이 누락된 걸까요?

2024-04-29 05:07 UTC, lee1684 commented on back-end/src/main/java/kr/co/ssalon/domain/service/MeetingService.java
> +        }
이 부분도 !랑 return이 누락된 것 같네요.

2024-04-29 05:07 UTC, lee1684 commented on back-end/src/main/java/kr/co/ssalon/domain/service/MeetingService.java
> +            Member roopMember = memberRepository.getReferenceById(memberMeeting.getMember().getId());
roopMember가 어떤 뜻일까요?

2024-04-29 05:08 UTC, lee1684 commented
제가 force push 한 브랜치이기 떄문에 지환님 로컬에 있는 feature/create-meeting 브랜치 지우시고 다시 git에 올라와 있는 브랜치 가져오셔야 합니다!

2024-04-29 05:10 UTC, lee1684 commented
병합 여부는 오늘 실습 시간에 테스트 해보고 나서 결정하죠.

2024-04-29 05:33 UTC, jihwankim129 commented on back-end/src/main/java/kr/co/ssalon/domain/service/MeetingService.java
> +        }
아하 저부분은 사실 예외 던질 곳인데 예외 어떻게 처리할지 안정해가지고, 일단 비워뒀는데 이미 작성하신거 보고 BadRequestException던지는걸로 바꿀게요

2024-04-29 05:34 UTC, jihwankim129 commented on back-end/src/main/java/kr/co/ssalon/domain/service/MeetingService.java
> +        }
위에랑 동일한 사유입니다 대신 저건 조건 문 안에 not 연산 넣은다음 예외 던질게요

2024-04-29 05:39 UTC, jihwankim129 commented on back-end/src/main/java/kr/co/ssalon/domain/service/MeetingService.java
> +            Member roopMember = memberRepository.getReferenceById(memberMeeting.getMember().getId());
멤버 엔티티에 있는 멤버미팅을 하나하나 지워주기 위해 쓴 코드고 각 멤버를 의미합니다.

2024-04-29 05:43 UTC, lee1684 commented on back-end/src/main/java/kr/co/ssalon/domain/service/MeetingService.java
> +            Member roopMember = memberRepository.getReferenceById(memberMeeting.getMember().getId());
roop이 어떤 단어의 줄임말일까요?

2024-04-29 06:02 UTC, jihwankim129 commented on back-end/src/main/java/kr/co/ssalon/domain/service/MeetingService.java
> +            Member roopMember = memberRepository.getReferenceById(memberMeeting.getMember().getId());
그냥 루프문으로 돌아다니면서 멤버에 접근하다 보니깐  말그대로 루프하다의 루프입니다

2024-04-29 06:03 UTC, lee1684 commented on back-end/src/main/java/kr/co/ssalon/domain/service/MeetingService.java
> +            Member roopMember = memberRepository.getReferenceById(memberMeeting.getMember().getId());
아하 그럼 loop가 맞겠네요!

2024-04-29 06:05 UTC, lee1684 commented on back-end/src/main/java/kr/co/ssalon/domain/service/MeetingService.java
> +            Member roopMember = memberRepository.getReferenceById(memberMeeting.getMember().getId());
그리고 밑에 코멘트를 못 보시고 푸쉬하셔서 커밋 로그가 다시 바뀌었는데 실습 시간에 다시 한 번 보죠.

2024-04-29 06:10 UTC, jihwankim129 commented on back-end/src/main/java/kr/co/ssalon/domain/service/MeetingService.java
> +            Member roopMember = memberRepository.getReferenceById(memberMeeting.getMember().getId());
그러게요 loop로 바꿔야하네 일단 저거 바꿔놓을게요

2024-04-29 06:12 UTC, lee1684 commented on back-end/src/main/java/kr/co/ssalon/domain/service/MeetingService.java
> +            Member roopMember = memberRepository.getReferenceById(memberMeeting.getMember().getId());
커밋 로그를 다시 리셋해야해서, loop 바꾸신 커밋은 푸쉬는 안 하셔도 될 것 같아요

2024-04-29 06:33 UTC, jihwankim129 commented
> 제가 force push 한 브랜치이기 때문에 지환님 로컬에 있는 feature/create-meeting 브랜치 지우시고 다시 git에 올라와 있는 브랜치 가져오셔야 합니다!

음 controller나 dto위치가 잘못된데 들어가있던 커밋이라 그냥 다 지워버렷엇는데 그러면 그냥 현재 브랜치에서 그런 내용들 지운거 커밋 추가할게요. 커밋이 뭔가 복구된것 같아서 잘못된 위치에 파일이 생겨버렷네요

2024-04-29 06:38 UTC, jihwankim129 commented
> > 제가 force push 한 브랜치이기 때문에 지환님 로컬에 있는 feature/create-meeting 브랜치 지우시고 다시 git에 올라와 있는 브랜치 가져오셔야 합니다!
> 
> 음 controller나 dto위치가 잘못된데 들어가있던 커밋이라 그냥 다 지워버렷엇는데 그러면 그냥 현재 브랜치에서 그런 내용들 지운거 커밋 추가할게요. 커밋이 뭔가 복구된것 같아서 잘못된 위치에 파일이 생겨버렷네요

미쳐 발견못하고 지운게 있을까봐 걱정되긴 한데 일단 눈에 보이는건 지워놨습니다. 막 controller위치가 web 디렉토리 아래에 있지 않다던가 불필요한 코드가 추가되어있다던가 한 내용들인데 눈에 보이는건 지워놨습니다.

2024-04-29 06:39 UTC, jihwankim129 commented
다른 코드들 보니깐 /api 가 추가되어있던데 저도 그런식으로 바꿀까요

2024-04-29 06:40 UTC, jihwankim129 commented
리베이스를 안하고 그냥 있던 내용들 다 지우고 새로 create-meeting 을 백엔드에서 가져와서 그거 기준으로 코드 다시 처음부터 짠거였어요

2024-04-29 06:49 UTC, jihwankim129 commented
음 지금 memberService 같은 부분들이 back-end와 내용이 다 달라 다 오류가 떠서 그냥 다시 원래대로 되돌려야할것같은데요

2024-04-29 06:50 UTC, jihwankim129 commented
아까 커밋 1개 있던 때로 다시 되돌릴 수 있나요

2024-04-29 07:25 UTC, jihwankim129 commented
잠시 수정할게 더 생겨서 아직 리뷰하지말아주세요

2024-04-29 08:38 UTC, jihwankim129 commented
meetingDTO가 id를 쓰도록 바뀌어 있더군요 그거에 맞춰서 한번 수정해보았습니다.

2024-05-01 05:58 UTC, closed without merging